### ISSUE TITLE
Configuration source cannot be reached, check source URL in uploaded anchor file

### ISSUE THREAD

**Issue by nilpoint** [vrk-kpa/xroad-public#14]
Hello,

I'm configuring a central server. After I add a signing key and the anchor is also generated, then I test the download url: http://ip/internalconf, but I got a 404 error. The error message in the /var/log/xroad/signer.log is:

```
ERROR [Signer-akka.actor.default-dispatcher-120] e.r.x.c.c.g.GlobalConfProviderFactory - Could not create an instance of GlobalConfProvider!
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
        at ee.ria.xroad.common.conf.globalconf.GlobalConfProviderFactory.createInstance(GlobalConfProviderFactory.java:69) ~[signer-1.0.jar:na]
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstance(GlobalConf.java:81) [signer-1.0.jar:na]
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getOcspFreshnessSeconds(GlobalConf.java:577) [signer-1.0.jar:na]
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFreshnessSeconds(OcspClientWorker.java:302) [signer-1.0.jar:na]
        at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:57) [signer-1.0.jar:na]
        at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:53) [signer-1.0.jar:na]
        at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:67) [signer-1.0.jar:na]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [signer-1.0.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) [signer-1.0.jar:na]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [signer-1.0.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [signer-1.0.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495) [signer-1.0.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [signer-1.0.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [signer-1.0.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [signer-1.0.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [signer-1.0.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [signer-1.0.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [signer-1.0.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [signer-1.0.jar:na]
Caused by: ee.ria.xroad.common.CodedException: MalformedGlobalConf.IOError: /etc/xroad/globalconf
        at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:203) ~[signer-1.0.jar:na]
        at ee.ria.xroad.common.ErrorCodes.translateWithPrefix(ErrorCodes.java:235) ~[signer-1.0.jar:na]
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:89) ~[signer-1.0.jar:na]
        ... 22 common frames omitted
Caused by: java.nio.file.NoSuchFileException: /etc/xroad/globalconf
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_91]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_91]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_91]
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[na:1.8.0_91]
        at java.nio.file.Files.newDirectoryStream(Files.java:589) ~[na:1.8.0_91]
at java.nio.file.Files.newDirectoryStream(Files.java:589) ~[na:1.8.0_91]
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectory.reload(ConfigurationDirectory.java:155) ~[signer-1.0.jar:na]
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectory.<init>(ConfigurationDirectory.java:126) ~[signer-1.0.jar:na]
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:86) ~[signer-1.0.jar:na]
        ... 22 common frames omitted
```

I can't locate the file /etc/xroad/globalconf, do I miss something not configured?

**Comment by iluwatar** [comment]
@nilpoint please check the following items:
- system settings - member classes -> there has to be at least one member class
- certification services -> at least one needs to be defined
- time stamping services -> at least one needs to be defined
- configuration management - signing keys -> key for signing internal and external configuration needs to be added
- members -> member that owns the central server needs to be defined
- system settings - management services -> service provider identifier needs to be defined
- in central server user interface the red bar with error messages (such as "Global configuration generation failing...") should no longer be visible at this point

**Comment by nilpoint** [comment]
@iluwatar Thank you， I've got that red bar disappeared.

**Comment by rajotico** [comment]
Hi,

I have compiled the deb packages, and I am trying to follow the steps you listed. I assume that this is all to be done a the central server, no security server exists yet because I need a anchor and configuration values which are only available once this url works (http://ip/intercanf).

I have defined a fake member (name, class and code) and used it under the service provider identifier. I still get this error under signer.log: 

ConfigurationException: Cannot locate configuration source /etc/xroad/conf.d/proxy.ini
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259) ~[signer-1.0.jar:na]
	at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.load(AbstractHierarchicalFileConfiguration.java:189) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.SystemPropertiesLoader.load(SystemPropertiesLoader.java:266) ~[signer-1.0.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_111]
	at ee.ria.xroad.common.SystemPropertiesLoader.load(SystemPropertiesLoader.java:221) ~[signer-1.0.jar:na]
	at ee.ria.xroad.signer.SignerMain.<clinit>(SignerMain.java:55) ~[signer-1.0.jar:na]
2016-12-25 20:36:52,307 INFO  [main] ee.ria.xroad.signer.SignerMain - Starting Signer on port 5558...
2016-12-25 20:36:53,168 INFO  [main] ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5559
2016-12-25 20:36:53,169 INFO  [main] org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT
2016-12-25 20:36:53,213 INFO  [main] o.e.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:5559
2016-12-25 20:36:58,833 ERROR [Signer-akka.actor.default-dispatcher-2] e.r.x.c.c.g.GlobalConfExtensions - Exception while fetching ocsp fetch interval configuration
ee.ria.xroad.common.CodedException: MalformedGlobalConf.IOError: /etc/xroad/globalconf
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:204) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.ErrorCodes.translateWithPrefix(ErrorCodes.java:228) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:63) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstance(GlobalConf.java:69) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:182) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:147) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:127) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:82) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:424) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:79) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:53) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:105) [signer-1.0.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165) [signer-1.0.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) [signer-1.0.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95) [signer-1.0.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [signer-1.0.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [signer-1.0.jar:na]
Caused by: java.nio.file.NoSuchFileException: /etc/xroad/globalconf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[na:1.8.0_111]
	at java.nio.file.Files.newDirectoryStream(Files.java:589) ~[na:1.8.0_111]
	at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectory.reload(ConfigurationDirectory.java:150) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.reload(CachingConfigurationDirectory.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.<init>(CachingConfigurationDirectory.java:67) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:60) ~[signer-1.0.jar:na]
	... 22 common frames omitted
2016-12-25 20:36:58,834 ERROR [Signer-akka.actor.default-dispatcher-2] e.r.x.c.c.g.GlobalConfExtensions - Exception while fetching ocsp fetch interval configuration
ee.ria.xroad.common.CodedException: MalformedGlobalConf.IOError: /etc/xroad/globalconf
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:204) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.ErrorCodes.translateWithPrefix(ErrorCodes.java:228) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:63) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstance(GlobalConf.java:69) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:182) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:147) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:127) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:82) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:424) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:81) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:53) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:105) [signer-1.0.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165) [signer-1.0.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) [signer-1.0.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95) [signer-1.0.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [signer-1.0.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [signer-1.0.jar:na]
Caused by: java.nio.file.NoSuchFileException: /etc/xroad/globalconf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[na:1.8.0_111]
	at java.nio.file.Files.newDirectoryStream(Files.java:589) ~[na:1.8.0_111]
	at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectory.reload(ConfigurationDirectory.java:150) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.reload(CachingConfigurationDirectory.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.<init>(CachingConfigurationDirectory.java:67) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:60) ~[signer-1.0.jar:na]
	... 22 common frames omitted

**Comment by kudramh** [comment]
@iluwatar: Could you please help me with this point? "* members -> member that owns the central server needs to be defined" I'm not sure about the parameter required...
Thanks In Advance
