### ISSUE TITLE
NoSuchFileException: /etc/xroad/globalconf

### ISSUE THREAD

**Issue by rajotico** [vrk-kpa/xroad-public#25]
Hi,
I have compiled the deb packages, and I am trying to follow the steps listed on issue #14 . I assume that these are all to be done a the central server, no security server exists yet because I need a anchor and configuration values which are only available once this url works (http://ip/intercanf).

I have created sigining keys, member classes, a test CA, TSA , OCSP service and a fake member (name, class and code).  I am using this fake member under the service provider identifier. I still get this error under signer.log:

2016-12-26 08:49:00,118 INFO  [main] ee.ria.xroad.signer.SignerMain - Starting Signer on port 5558...
2016-12-26 08:49:03,677 INFO  [main] ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5559
2016-12-26 08:49:03,683 INFO  [main] org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT
2016-12-26 08:49:03,759 INFO  [main] o.e.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:5559
2016-12-26 08:49:10,498 ERROR [Signer-akka.actor.default-dispatcher-6] e.r.x.c.c.g.GlobalConfExtensions - Exception while fetching ocsp fetch interval configuration
ee.ria.xroad.common.CodedException: MalformedGlobalConf.IOError: /etc/xroad/globalconf
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:204) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.ErrorCodes.translateWithPrefix(ErrorCodes.java:228) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:63) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstance(GlobalConf.java:69) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:182) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:147) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:127) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:82) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:424) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:79) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:53) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:105) [signer-1.0.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165) [signer-1.0.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) [signer-1.0.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95) [signer-1.0.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [signer-1.0.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [signer-1.0.jar:na]
Caused by: java.nio.file.NoSuchFileException: /etc/xroad/globalconf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[na:1.8.0_111]
	at java.nio.file.Files.newDirectoryStream(Files.java:589) ~[na:1.8.0_111]
	at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectory.reload(ConfigurationDirectory.java:150) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.reload(CachingConfigurationDirectory.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.<init>(CachingConfigurationDirectory.java:67) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:60) ~[signer-1.0.jar:na]
	... 22 common frames omitted
2016-12-26 08:49:10,510 ERROR [Signer-akka.actor.default-dispatcher-6] e.r.x.c.c.g.GlobalConfExtensions - Exception while fetching ocsp fetch interval configuration
ee.ria.xroad.common.CodedException: MalformedGlobalConf.IOError: /etc/xroad/globalconf
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:204) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.ErrorCodes.translateWithPrefix(ErrorCodes.java:228) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:63) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstance(GlobalConf.java:69) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:182) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:147) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:127) [signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:82) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:424) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:81) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:53) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:105) [signer-1.0.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165) [signer-1.0.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) [signer-1.0.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95) [signer-1.0.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [signer-1.0.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [signer-1.0.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [signer-1.0.jar:na]
Caused by: java.nio.file.NoSuchFileException: /etc/xroad/globalconf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[na:1.8.0_111]
	at java.nio.file.Files.newDirectoryStream(Files.java:589) ~[na:1.8.0_111]
	at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectory.reload(ConfigurationDirectory.java:150) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.reload(CachingConfigurationDirectory.java:138) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.<init>(CachingConfigurationDirectory.java:67) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:60) ~[signer-1.0.jar:na]
	... 22 common frames omitted

**Comment by iluwatar** [comment]
> I have compiled the deb packages, and I am trying to follow the steps listed on issue #14 . I assume that these are all to be done a the central server, no security server exists yet because I need a anchor and configuration values which are only available once this url works (http://ip/intercanf).

Yes, all the steps are done in the central server user interface. Once the configuration is complete the red bars with error messages should disappear.

> I have created sigining keys, member classes, a test CA, TSA , OCSP service and a fake member (name, class and code). I am using this fake member under the service provider identifier. I still get this error under signer.log:

Is the central server generating the global configuration successfully i.e. have the red bars with error messages disappeared from the central server user interface? Also looking at `/var/log/xroad/jetty/jetty.log` can reveal  what is wrong.

**Comment by rajotico** [comment]
var/log/xroad/jetty/jetty.log shows this error:
java.lang.NoClassDefFoundError: Could not initialize class org.jruby.runtime.scope.ManyVarsDynamicScope
Caused by: java.lang.RuntimeException: BUG: could not initialize constructor handle
	at org.jruby.runtime.scope.ManyVarsDynamicScope.<clinit>(ManyVarsDynamicScope.java:39)

**Comment by rajotico** [comment]
FIXED!

the WAR was including a jruby-core 9.1.6 jar file, removed that and left the 1.7.25 version, that fixed my problem.
