### ISSUE TITLE
Error on build the project

### ISSUE THREAD

**Issue by belang** [vrk-kpa/xroad-public#4]
I build the project on Ubuntu 16.04 server, and meet some Errors.

The following is the printed log:

Warning! PATH is not properly set up, '/home/putian001/.rvm/gems/jruby-1.7.22/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use jruby-1.7.22'.
Using /home/putian001/.rvm/gems/jruby-1.7.22
---- verifier xjc @ configuration phase
---- monitoring xjc @ configuration phase
:addons:compileJava UP-TO-DATE
:addons:processResources UP-TO-DATE
:addons:classes UP-TO-DATE
:addons:jar UP-TO-DATE
:addons:sourcesJar UP-TO-DATE
:addons:assemble UP-TO-DATE
:addons:checkstyleMain UP-TO-DATE
:addons:compileTestJava UP-TO-DATE
:addons:processTestResources UP-TO-DATE
:addons:testClasses UP-TO-DATE
:addons:checkstyleTest UP-TO-DATE
:addons:pmdMain UP-TO-DATE
:addons:pmdTest UP-TO-DATE
:addons:test UP-TO-DATE
:addons:check UP-TO-DATE
:addons:build UP-TO-DATE
:common-util:createDirs UP-TO-DATE
:common-util:xjc UP-TO-DATE
:common-util:compileJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:common-util:make
for i in passwordstore ;\
do \
	( echo $i && cd $i && make && make install ) || exit 1 ;\
done
passwordstore
make[1]: Entering directory '/home/putian001/work/eID/xroad-public-master/src/passwordstore'
Cannot create dependency info for test_globalstring.c yet
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/putian001/work/eID/xroad-public-master/src/passwordstore'
make[1]: Entering directory '/home/putian001/work/eID/xroad-public-master/src/passwordstore'
Cannot create dependency info for test_globalstring.c yet
(mkdir -p /home/putian001/work/eID/xroad-public-master/src/lib && \
	install -m 644  libpasswordstore.so /home/putian001/work/eID/xroad-public-master/src/lib) || exit 1
make[1]: Leaving directory '/home/putian001/work/eID/xroad-public-master/src/passwordstore'
:common-util:processResources UP-TO-DATE
:common-util:classes
:common-util:jar UP-TO-DATE
:async-db:compileJava UP-TO-DATE
:async-db:processResources UP-TO-DATE
:async-db:classes UP-TO-DATE
:async-db:jar UP-TO-DATE
:common-db:compileJava UP-TO-DATE
:common-db:processResources UP-TO-DATE
:common-db:classes UP-TO-DATE
:common-db:jar UP-TO-DATE
:common-verifier:processResources UP-TO-DATE
:common-verifier:createDirs UP-TO-DATE
:common-verifier:xjc
---- verifier xjc @ execution phase
[ant:xjc] [WARNING] schema_reference.4: Failed to read schema document 'identifiers.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
[ant:xjc]   line 7 of file:/home/putian001/work/eID/xroad-public-master/src/common-verifier/build/resources/main/ocsp-nextupdate-conf.xsd
[ant:xjc] 
[ant:xjc] [WARNING] java.io.FileNotFoundException: /home/putian001/work/eID/xroad-public-master/src/common-verifier/build/resources/main/identifiers.xsd (No such file or directory)
[ant:xjc]   line 7 of file:/home/putian001/work/eID/xroad-public-master/src/common-verifier/build/resources/main/ocsp-nextupdate-conf.xsd
[ant:xjc] 
:common-verifier:compileJavaNote: /home/putian001/work/eID/xroad-public-master/src/common-verifier/src/main/java/ee/ria/xroad/common/signature/SignatureVerifier.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:common-verifier:classes
:common-verifier:jar UP-TO-DATE
:signer-protocol:compileJava UP-TO-DATE
:signer-protocol:processResources UP-TO-DATE
:signer-protocol:classes UP-TO-DATE
:signer-protocol:jar UP-TO-DATE
:common-ui:compileJava UP-TO-DATE
:common-ui:processResources UP-TO-DATE
:common-ui:classes UP-TO-DATE
:common-ui:jar UP-TO-DATE
:serverconf:compileJava UP-TO-DATE
:serverconf:processResources UP-TO-DATE
:serverconf:classes UP-TO-DATE
:serverconf:jar UP-TO-DATE
:proxy-ui:compileJava UP-TO-DATE
:proxy-ui:processResources UP-TO-DATE
:proxy-ui:classes UP-TO-DATE
:proxy-ui:jar UP-TO-DATE
:proxy-ui:sourcesJar UP-TO-DATE
:proxy-ui:assemble UP-TO-DATE
:proxy-ui:checkRubySource
0.32.0
Source inspection report will be generated into '/home/putian001/work/eID/xroad-public-master/src/proxy-ui/build/rubocop_report.txt'
:proxy-ui:checkstyleMain UP-TO-DATE
:proxy-ui:compileTestJava UP-TO-DATE
:proxy-ui:processTestResources UP-TO-DATE
:proxy-ui:testClasses UP-TO-DATE
:proxy-ui:checkstyleTest UP-TO-DATE
:proxy-ui:licenseMain UP-TO-DATE
:proxy-ui:licenseTest UP-TO-DATE
:proxy-ui:license UP-TO-DATE
:proxy-ui:pmdMain UP-TO-DATE
:proxy-ui:pmdTest UP-TO-DATE
:proxy-ui:test UP-TO-DATE
:proxy-ui:check
:proxy-ui:copyCommon UP-TO-DATE
:proxy-ui:copyDeps UP-TO-DATE
:proxy-ui:build
:proxy-ui:generateJsTranslations
:proxy-ui:warblewarning: Bundler `path' components are not currently supported.
The `common-ui-0.0.1' component was not bundled.
Your application may fail to boot!
rm -f build/libs/proxy-ui.war

Creating build/libs/proxy-ui.war
:addons:buildall
:asic-util:compileJava UP-TO-DATE
:asic-util:processResources UP-TO-DATE
:asic-util:classes UP-TO-DATE
:asic-util:jar UP-TO-DATE
:asic-util:sourcesJar UP-TO-DATE
:asic-util:assemble UP-TO-DATE
:asic-util:checkstyleMain UP-TO-DATE
:common-test:compileJava UP-TO-DATE
:common-test:processResources UP-TO-DATE
:common-test:classes UP-TO-DATE
:common-test:jar UP-TO-DATE
:asic-util:compileTestJava UP-TO-DATE
:asic-util:processTestResources UP-TO-DATE
:asic-util:testClasses UP-TO-DATE
:asic-util:checkstyleTest UP-TO-DATE
:asic-util:licenseMain UP-TO-DATE
:asic-util:licenseTest UP-TO-DATE
:asic-util:license UP-TO-DATE
:asic-util:pmdMain UP-TO-DATE
:asic-util:pmdTest UP-TO-DATE
:asic-util:test UP-TO-DATE
:asic-util:check UP-TO-DATE
:asic-util:build UP-TO-DATE
:asic-util:buildall
:asicverifier:compileJava UP-TO-DATE
:asicverifier:processResources UP-TO-DATE
:asicverifier:classes UP-TO-DATE
:asicverifier:jar UP-TO-DATE
:asicverifier:sourcesJar UP-TO-DATE
:asicverifier:assemble UP-TO-DATE
:asicverifier:checkstyleMain UP-TO-DATE
:asicverifier:compileTestJava UP-TO-DATE
:asicverifier:processTestResources UP-TO-DATE
:asicverifier:testClasses UP-TO-DATE
:asicverifier:checkstyleTest UP-TO-DATE
:asicverifier:licenseMain UP-TO-DATE
:asicverifier:licenseTest UP-TO-DATE
:asicverifier:license UP-TO-DATE
:asicverifier:pmdMain UP-TO-DATE
:asicverifier:pmdTest UP-TO-DATE
:asicverifier:test UP-TO-DATE
:asicverifier:check UP-TO-DATE
:asicverifier:build UP-TO-DATE
:asicverifier:buildall
:async-db:sourcesJar UP-TO-DATE
:async-db:assemble UP-TO-DATE
:async-db:checkstyleMain UP-TO-DATE
:async-db:compileTestJava UP-TO-DATE
:async-db:processTestResources UP-TO-DATE
:async-db:testClasses UP-TO-DATE
:async-db:checkstyleTest UP-TO-DATE
:async-db:licenseMain UP-TO-DATE
:async-db:licenseTest UP-TO-DATE
:async-db:license UP-TO-DATE
:async-db:pmdMain UP-TO-DATE
:async-db:pmdTest UP-TO-DATE
:async-db:test UP-TO-DATE
:async-db:check UP-TO-DATE
:async-db:build UP-TO-DATE
:async-db:buildall
:async-sender:compileJava UP-TO-DATE
:async-sender:processResources UP-TO-DATE
:async-sender:classes UP-TO-DATE
:async-sender:jar UP-TO-DATE
:async-sender:sourcesJar UP-TO-DATE
:async-sender:assemble UP-TO-DATE
:async-sender:checkstyleMain UP-TO-DATE
:async-sender:compileTestJava UP-TO-DATE
:async-sender:processTestResources UP-TO-DATE
:async-sender:testClasses UP-TO-DATE
:async-sender:checkstyleTest UP-TO-DATE
:async-sender:licenseMain UP-TO-DATE
:async-sender:licenseTest UP-TO-DATE
:async-sender:license UP-TO-DATE
:async-sender:pmdMain UP-TO-DATE
:async-sender:pmdTest UP-TO-DATE
:async-sender:test UP-TO-DATE
:async-sender:check UP-TO-DATE
:async-sender:build UP-TO-DATE
:async-sender:buildall
:common-db:sourcesJar UP-TO-DATE
:common-db:assemble UP-TO-DATE
:common-db:checkstyleMain UP-TO-DATE
:common-db:compileTestJava UP-TO-DATE
:common-db:processTestResources UP-TO-DATE
:common-db:testClasses UP-TO-DATE
:common-db:checkstyleTest UP-TO-DATE
:common-db:licenseMain UP-TO-DATE
:common-db:licenseTest UP-TO-DATE
:common-db:license UP-TO-DATE
:common-db:pmdMain UP-TO-DATE
:common-db:pmdTest UP-TO-DATE
:common-db:test UP-TO-DATE
:common-db:check UP-TO-DATE
:common-db:build UP-TO-DATE
:common-db:buildall
:common-messagelog:compileJava UP-TO-DATE
:common-messagelog:processResources UP-TO-DATE
:common-messagelog:classes UP-TO-DATE
:common-messagelog:jar UP-TO-DATE
:common-messagelog:sourcesJar UP-TO-DATE
:common-messagelog:assemble UP-TO-DATE
:common-messagelog:checkstyleMain UP-TO-DATE
:common-messagelog:compileTestJava UP-TO-DATE
:common-messagelog:processTestResources UP-TO-DATE
:common-messagelog:testClasses UP-TO-DATE
:common-messagelog:checkstyleTest UP-TO-DATE
:common-messagelog:licenseMain UP-TO-DATE
:common-messagelog:licenseTest UP-TO-DATE
:common-messagelog:license UP-TO-DATE
:common-messagelog:pmdMain UP-TO-DATE
:common-messagelog:pmdTest UP-TO-DATE
:common-messagelog:test UP-TO-DATE
:common-messagelog:check UP-TO-DATE
:common-messagelog:build UP-TO-DATE
:common-messagelog:buildall
:common-test:sourcesJar UP-TO-DATE
:common-test:assemble UP-TO-DATE
:common-test:checkstyleMain UP-TO-DATE
:common-test:compileTestJava UP-TO-DATE
:common-test:processTestResources UP-TO-DATE
:common-test:testClasses UP-TO-DATE
:common-test:checkstyleTest UP-TO-DATE
:common-test:licenseMain UP-TO-DATE
:common-test:licenseTest UP-TO-DATE
:common-test:license UP-TO-DATE
:common-test:pmdMain UP-TO-DATE
:common-test:pmdTest UP-TO-DATE
:common-test:test UP-TO-DATE
:common-test:check UP-TO-DATE
:common-test:build UP-TO-DATE
:common-test:buildall
:common-ui:sourcesJar UP-TO-DATE
:common-ui:assemble UP-TO-DATE
:common-ui:checkRubySource
0.32.0
Source inspection report will be generated into '/home/putian001/work/eID/xroad-public-master/src/common-ui/build/rubocop_report.txt'
:common-ui:checkstyleMain UP-TO-DATE
:common-ui:compileTestJava UP-TO-DATE
:common-ui:processTestResources UP-TO-DATE
:common-ui:testClasses UP-TO-DATE
:common-ui:checkstyleTest UP-TO-DATE
:common-ui:licenseMain UP-TO-DATE
:common-ui:licenseTest UP-TO-DATE
:common-ui:license UP-TO-DATE
:common-ui:pmdMain UP-TO-DATE
:common-ui:pmdTest UP-TO-DATE
:common-ui:test UP-TO-DATE
:common-ui:check
:common-ui:copyDeps UP-TO-DATE
:common-ui:build
:common-ui:buildall
:common-util:sourcesJar
:common-util:assemble
:common-util:checkstyleMain
:common-util:compileTestJava UP-TO-DATE
:common-util:processTestResources UP-TO-DATE
:common-util:testClasses UP-TO-DATE
:common-util:checkstyleTest UP-TO-DATE
:common-util:licenseMain SKIPPED
:common-util:licenseTestJava UP-TO-DATE
:common-util:licenseTest UP-TO-DATE
:common-util:license UP-TO-DATE
:common-util:pmdMain
4 PMD rule violations were found. See the report at: file:///home/putian001/work/eID/xroad-public-master/src/common-util/build/reports/pmd/main.html
:common-util:pmdTest UP-TO-DATE
:common-util:test UP-TO-DATE
:common-util:check
:common-util:build
:common-util:buildall
:common-verifier:sourcesJar
:common-verifier:assemble
:common-verifier:checkstyleMain
:common-verifier:compileTestJava UP-TO-DATE
:common-verifier:processTestResources UP-TO-DATE
:common-verifier:testClasses UP-TO-DATE
:common-verifier:checkstyleTest UP-TO-DATE
:common-verifier:licenseMain SKIPPED
:common-verifier:licenseTestJava UP-TO-DATE
:common-verifier:licenseTest UP-TO-DATE
:common-verifier:license UP-TO-DATE
:common-verifier:pmdMain
:common-verifier:pmdTest UP-TO-DATE
:common-verifier:test UP-TO-DATE
:common-verifier:check
:common-verifier:build
:common-verifier:buildall
:configuration-client:compileJava UP-TO-DATE
:configuration-client:processResources UP-TO-DATE
:configuration-client:classes UP-TO-DATE
:configuration-client:jar SKIPPED
:configuration-client:sourcesJar UP-TO-DATE
:configuration-client:assemble UP-TO-DATE
:configuration-client:checkstyleMain UP-TO-DATE
:configuration-client:compileTestJava
:configuration-client:processTestResources UP-TO-DATE
:configuration-client:testClasses
:configuration-client:checkstyleTest
:configuration-client:licenseMain UP-TO-DATE
:configuration-client:licenseTest UP-TO-DATE
:configuration-client:license UP-TO-DATE
:configuration-client:pmdMain UP-TO-DATE
:configuration-client:pmdTest
:configuration-client:test

ee.ria.xroad.common.conf.globalconf.ConfigurationParserTest > parseConf FAILED
    ee.ria.xroad.common.CodedException at ConfigurationParserTest.java:152

ee.ria.xroad.common.conf.globalconf.ConfigurationClientTest > downloadDetachedConf FAILED
    ee.ria.xroad.common.CodedException at ConfigurationClientTest.java:88

ee.ria.xroad.common.conf.globalconf.ConfigurationClientTest > downloadSimpleConf FAILED
    ee.ria.xroad.common.CodedException at ConfigurationClientTest.java:64

30 tests completed, 3 failed
:configuration-client:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':configuration-client:test'.
> There were failing tests. See the report at: file:///home/putian001/work/eID/xroad-public-master/src/configuration-client/build/reports/tests/index.html

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':configuration-client:test'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/putian001/work/eID/xroad-public-master/src/configuration-client/build/reports/tests/index.html
	at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1129)
	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:567)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 46 more

BUILD FAILED

Total time: 2 mins 58.756 secs

**Comment by belang** [comment]
The report files:
downloadDetachedConf::
OutdatedGlobalConf: Configuration instance EE expired on 2016-05-21T01:42:55.000+08:00 
    at ee.ria.xroad.common.conf.globalconf.ConfigurationParser$ConfigurationPartContentHandler.verifyConfUpToDate(ConfigurationParser.java:329)
    at ee.ria.xroad.common.conf.globalconf.ConfigurationParser$ConfigurationPartContentHandler.body(ConfigurationParser.java:312)
    at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:133)

Standard output::
15:44:06.144 [Test worker] INFO  e.r.x.c.c.g.ConfigurationDownloader - Downloading configuration from src/test/resources/test-conf-detached.txt 
15:44:07.512 [Test worker] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog 
15:44:08.067 [Test worker] ERROR e.r.x.c.c.g.ConfigurationClient - Failed to download configuration from any configuration location: 
    location: src/test/resources/test-conf-detached.txt; error: OutdatedGlobalConf: Configuration instance EE expired on 2016-05-21T01:42:55.000+08:00 
 
15:44:08.349 [Test worker] INFO  e.r.x.c.c.g.ConfigurationDownloader - Downloading configuration from src/test/resources/test-conf-malformed.txt 
15:44:08.369 [Test worker] ERROR e.r.x.c.c.g.ConfigurationClient - Failed to download configuration from any configuration location: 
    location: src/test/resources/test-conf-malformed.txt; error: MalformedGlobalConf: Configuration instance EE is missing signed data expiration date 
 
15:44:08.575 [Test worker] INFO  e.r.x.c.c.g.ConfigurationDownloader - Downloading configuration from src/test/resources/test-conf-simple.txt 
15:44:08.591 [Test worker] ERROR e.r.x.c.c.g.ConfigurationClient - Failed to download configuration from any configuration location: 
    location: src/test/resources/test-conf-simple.txt; error: OutdatedGlobalConf: Configuration instance EE expired on 2016-05-21T01:42:55.000+08:00

**Comment by iluwatar** [comment]
The reason for the failing tests is expired test data (Expire-date: 2016-05-20T17:42:55). You can generate new test data with https://github.com/vrk-kpa/xroad-public/blob/master/src/configuration-client/src/test/java/ee/ria/xroad/common/conf/globalconf/GenerateTestData.java. Set the date on line 109 to some future date and run the Java main to regenerate the test data.

**Comment by belang** [comment]
thanks!!!!
