### ISSUE TITLE
Upgrade BouncyCastle to version 1.54

### ISSUE THREAD

**Issue by mihkels** [vrk-kpa/xroad-public#5]
Is it possible to update project BouncyCastle version to 1.54?

Main issue is we use `asiceverifier` as dependency in our Maven project but other validation Java lib-s have been upgraded to 1.54 and this causes problems with our Maven classloader.

``` java
java.lang.NoSuchMethodError: org.bouncycastle.cert.ocsp.RespID.toASN1Object()Lorg/bouncycastle/asn1/ocsp/ResponderID;

    at ee.ria.xroad.common.ocsp.OcspVerifier.getOcspCert(OcspVerifier.java:232)
    at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidity(OcspVerifier.java:121)
    at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidityAndStatus(OcspVerifier.java:69)
    at ee.ria.xroad.common.cert.CertChainVerifier.verifyOcspResponses(CertChainVerifier.java:143)
    at ee.ria.xroad.common.cert.CertChainVerifier.verifyImpl(CertChainVerifier.java:116)
    at ee.ria.xroad.common.cert.CertChainVerifier.verify(CertChainVerifier.java:104)
    at ee.ria.xroad.common.signature.SignatureVerifier.verifyCertificateChain(SignatureVerifier.java:304)
    at ee.ria.xroad.common.signature.SignatureVerifier.verify(SignatureVerifier.java:224)
    at ee.ria.xroad.common.asic.AsicContainerVerifier.verify(AsicContainerVerifier.java:122)
    at ee.openeid.siva.xroad.XROADValidationService.validateDocument(XROADValidationService.java:39)
```

**Comment by iluwatar** [comment]
BouncyCastle has been updated to 1.54 version in our develop branch and the change will be included in the next release.

**Comment by mihkels** [comment]
When will be the next release?

**Comment by iluwatar** [comment]
We are aiming for mid September.

**Comment by hanhaka** [comment]
Version 6.7.13 includes fix for this issue.
Issue resolved, closing it.
